blog/api/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import ArticleViewSet, UserViewSet

app_name = "api"

router = routers.SimpleRouter()
# router.register('users', UserViewSet)
router.register('articles', ArticleViewSet, basename='article')
router.register('users', UserViewSet, basename='user')


urlpatterns = [
    path('',include(router.urls)),
]

blog/blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetail , CategoryList , AuthorList, ArticlePreview, SearchList

app_name = "blog"
urlpatterns = [
    path('', ArticleListView.as_view(), name="ArticleListView"),
    path('page/<int:page>', ArticleListView.as_view(), name="ArticleListView"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name="articledetail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="CategoryView"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="CategoryView"),
    path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
    path('search/', SearchList.as_view(), name="search"),
    path('search/page/<int:page>', SearchList.as_view(), name="search"),

]

blog/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from . import settings
from django.conf.urls import include
from account.views import Login, Register, activate


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>)/', activate, name='activate'),
    path('comment/', include('comment.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
    path('', include('blog_setting.urls')),
    path('account/', include('account.urls')),
    path('api/', include('api.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls'))
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils import timezone
from extensions.utils import jalali_converter
from django.utils.html import format_html
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


# Create your models here.
class CategoryManager(models.Manager):
    
    def get_active_category(self):
        active = self.filter(status=True)
        return active
    
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آدرس آی پی")    



class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=150, verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='ادرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(default=0, verbose_name='پوزیشن')
    objects = CategoryManager()
    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural='دسته بندی ها'
        ordering=[ 'parent__id','position']

    def __str__(self):
        return self.title


class ArticleManager(models.Manager):

    def get_published_article(self):
        published = self.filter(status='p') 
        return published



class Article(models.Model):
    
    STATUS_CHOICES = (
        ('d','چک نویس'), # draft
        ('p','منتشر شده'), #publish
        ('i','در حال بررسی'), #investigation
        ('b','برگشت داده شده'), #back

    )

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='article', verbose_name='نویسنده')
    title = models.CharField(max_length = 150, verbose_name='عنوان')
    slug = models.SlugField(max_length= 150, unique = True , verbose_name='ادرس لینک')
    category = models.ManyToManyField(Category,related_name='articles',verbose_name='دسته بندی')
    description = models.TextField(verbose_name='توضیحات')
    thumpnail = models.ImageField(upload_to = 'blog-images',verbose_name='تصویر')
    publish = models.DateTimeField(default = timezone.now,verbose_name='منتشر شده')
    created = models.DateTimeField(auto_now_add=True,verbose_name='ساخته شده')
    updated = models.DateTimeField(auto_now=True,verbose_name='بروز رسانی شده')
    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    status = models.CharField(max_length= 1,choices=STATUS_CHOICES,verbose_name='وضعیت')
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name="hits", verbose_name="بازدید ها")
    objects = ArticleManager()

    class Meta:
         verbose_name = 'مقاله'
         verbose_name_plural = 'مقالات'
         ordering = ['-publish']
    
    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'تاریخ انتشار'

    def get_absolute_url(self):
        return reverse("account:home")
    
    def jupdated(self):
        return jalali_converter(self.updated)
    jupdated.short_description = 'تاریخ بروز رسانی'

    def thumpnail_tag(self):
        return format_html("<img src='{}' width=95 height=75 style='border-radius: 5px;'>".format(self.thumpnail.url))
    thumpnail_tag.short_description = 'عکس مقاله'

    def category_to_str(self):
        return " ,".join([category.title for category in self.category.get_active_category()])
    category_to_str.short_description='دسته بندی'
    
class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


    

    

    

blog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from account.models import User
from django.db.models import Count, Q
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from account.mixins import AuthorAccessMixin
from datetime import datetime, timedelta
from django.db.models import Q
# Create your views here.


class ArticleListView(ListView):
    last_month = datetime.today() - timedelta(days=30)
    queryset = Article.objects.get_published_article()
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        last_month = datetime.today() - timedelta(days=30)
        context['popular_articles'] = Article.objects.get_published_article().annotate(count=Count('hits', filter=Q(articlehit__created__gte=last_month))).order_by('-count', '-publish')[:5]
        return context



#Q(articlehit__year=2020)
#Q(articlehit__month=12)


class ArticleDetail(DetailView):

    def get_object(self):
        slug = self.kwargs.get('slug')
        article = Article.objects.get_published_article()
        article = get_object_or_404(article, slug=slug)

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)

        return article


class ArticlePreview(AuthorAccessMixin, DetailView):

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)


class CategoryList(ListView):
    paginate_by = 2
    template_name = 'blog/category_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(
            Category.objects.get_active_category(), slug=slug)
        return category.articles.get_published_article()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 2
    template_name = 'blog/author_list.html'

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.article.get_published_article()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


class SearchList(ListView):
    paginate_by = 2
    template_name = 'blog/search_list.html'

    def get_queryset(self):
        global author
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

blog/templates/blog/article_detail.html
{% extends 'shared/base.html' %}
{% load comment_tags %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}

{% block main %}

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{article.thumpnail.url}}')">
        <div class="overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <div class="post-heading">
                <h1>{{article.title}}</h1>
                {% if article.is_special %}
                <span class="badge badge-danger" style="font-size: 18px;">ویژه</span>
              {% endif %}
            </h2>
                <h2 class="subheading"></h2>
                <span class="meta"> منتشر شده توسط 
                  <a href="{% url 'blog:author' article.author %}"> {{ article.author.get_full_name }}</a>
                    در {{ article.publish|naturaltime }}  </span>
                    <div>{% ratings object %}</div>
                    <div>بازدید ها :{{ object.hits.count }}</div>
              </div>
            </div>
          </div>
        </div>
      </header>

  <!-- Main Content -->
  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
          <aside>
            {% popular_articles %}
            {% hot_articles %}
          </aside>
          {% if object.is_special %}
              {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                  {{article.description|safe}}
              {% else %}
                  {{ article.description|striptags|truncatewords:100 }}
                  <p class="alert alert-warning"> این مقاله ویژه است و باید <a class="alert-link" href="#">اشتراک ویژه</a> خریداری شود !</p>   
              {% endif %}
          {% else %}
              {{article.description|safe}} 
          {% endif %}
          {% render_comments object request %}
          {% include_bootstrap %}   
        </div>
      </div>
    </div>
  </article>
    
{% endblock main %}

blog/templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}
{% endblock header %}



{% block previous_page_url %}
    {% url 'blog:ArticleListView' page_obj.previous_page_number %}
{% endblock %}



{% block active_page %}
    {% url 'blog:ArticleListView' page %}
{% endblock %}



{% block unactive_page %}
    {% url 'blog:ArticleListView' page %}
{% endblock %}


{% block next_page_url %}
    {% url 'blog:ArticleListView' page_obj.next_page_number %}
{% endblock %}

blog/templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">نویسنده {{ author.get_full_name }}</h3>
{% endblock header %}



{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}



{% block active_page %}
    {% url 'blog:author' author.username page %}
{% endblock %}



{% block unactive_page %}
    {% url 'blog:author' author.username page %}
{% endblock %}


{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

blog/templates/blog/category_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">دسته بندی در {{ category.title }}</h3>
{% endblock header %}



{% block previous_page_url %}
    {% url 'blog:CategoryView' category.slug page_obj.previous_page_number %}
{% endblock %}



{% block active_page %}
    {% url 'blog:CategoryView' category.slug page %}
{% endblock %}



{% block unactive_page %}
    {% url 'blog:CategoryView' category.slug page %}
{% endblock %}


{% block next_page_url %}
    {% url 'blog:CategoryView' category.slug page_obj.next_page_number %}
{% endblock %}

blog/templates/blog/list.html
{% extends 'shared/base.html' %}
{% load render_partial %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}


{% block main %}

  <!-- Page Header -->
{% render_partial 'settings:header' %}

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
       {% block header %} {% endblock header %}
        <aside>
          {% popular_articles %}
          {% hot_articles %}
        </aside>
        {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'blog:articledetail' article.slug %}">
              <h2 class="post-title">
                {{article.title}}
                {% if article.is_special %}
                  <span class="badge badge-danger" style="font-size: 18px;">ویژه</span>
                {% endif %}
              </h2>
              <div>{% ratings article %}</div>
              
              <h3 class="post-subtitle text-justify">
              {{ article.description|striptags|truncatewords:100 }}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط
              <a href="{% url 'blog:author' article.author %}"> {{ article.author.get_full_name }}</a>
              {{ article.publish|naturaltime }}</p>        
            
            <div>
              {% for category in article.category.get_active_category %}
                <a href="{% url 'blog:CategoryView' category.slug %}">#{{ category.title }} </a> 
              {% endfor %}
            </div>
            <div>بازدید ها :{{ article.hits.count }}</div>
          </div>
          <hr>
        {% empty %}
          <p>متاسفانه محتوایی برای نمایش وجود ندارد.</p>
        {% endfor %}

      <!-- Pager -->
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="{% block previous_page_url %}{% endblock %}">صفحه قبل</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">صفحه قبل</a></li>
          {% endif %}
          
          {% for page in paginator.page_range %}
            
            {% if page == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="{% block active_page %}{% endblock %}">{{ page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% block unactive_page %}{% endblock %}">{{ page }}</a></li>
            {% endif %}
            
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="{% block next_page_url %}{% endblock %}">صفحه بعد</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">صفحه بعد</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>
{% endblock main %}

blog/templates/blog/search_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">جست و جو : {{ search }}</h3>
{% endblock header %}



{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}?q={{search}}
{% endblock %}



{% block active_page %}
    {% url 'blog:search' page %}?q={{search}}
{% endblock %}



{% block unactive_page %}
    {% url 'blog:search' page %}?q={{search}}
{% endblock %}


{% block next_page_url %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}